# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_parameter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editParameter(object):
    def setupUi(self, editParameter):
        editParameter.setObjectName("editParameter")
        editParameter.resize(430, 248)
        self.buttonBox = QtWidgets.QDialogButtonBox(editParameter)
        self.buttonBox.setGeometry(QtCore.QRect(140, 200, 151, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(editParameter)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 351, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deviceLayout = QtWidgets.QHBoxLayout()
        self.deviceLayout.setObjectName("deviceLayout")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.deviceLayout.addItem(spacerItem)
        self.deviceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.deviceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.deviceLabel.setObjectName("deviceLabel")
        self.deviceLayout.addWidget(self.deviceLabel)
        self.deviceBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.deviceBox.setObjectName("deviceBox")
        self.deviceLayout.addWidget(self.deviceBox)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.deviceLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.deviceLayout)
        self.paramsLayout = QtWidgets.QHBoxLayout()
        self.paramsLayout.setObjectName("paramsLayout")
        self.activeParamsLayout = QtWidgets.QVBoxLayout()
        self.activeParamsLayout.setObjectName("activeParamsLayout")
        self.activeParamsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.activeParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.activeParamsLabel.setObjectName("activeParamsLabel")
        self.activeParamsLayout.addWidget(self.activeParamsLabel)
        self.activeParamsWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.activeParamsWidget.setObjectName("activeParamsWidget")
        self.activeParamsLayout.addWidget(self.activeParamsWidget)
        self.paramsLayout.addLayout(self.activeParamsLayout)
        self.paramButtonLayout = QtWidgets.QVBoxLayout()
        self.paramButtonLayout.setObjectName("paramButtonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.paramButtonLayout.addItem(spacerItem2)
        self.addParamButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addParamButton.sizePolicy().hasHeightForWidth())
        self.addParamButton.setSizePolicy(sizePolicy)
        self.addParamButton.setObjectName("addParamButton")
        self.paramButtonLayout.addWidget(self.addParamButton)
        self.delParamButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delParamButton.setObjectName("delParamButton")
        self.paramButtonLayout.addWidget(self.delParamButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.paramButtonLayout.addItem(spacerItem3)
        self.paramsLayout.addLayout(self.paramButtonLayout)
        self.allParamsLayout = QtWidgets.QVBoxLayout()
        self.allParamsLayout.setObjectName("allParamsLayout")
        self.allParamsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.allParamsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.allParamsLabel.setObjectName("allParamsLabel")
        self.allParamsLayout.addWidget(self.allParamsLabel)
        self.allParamsWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.allParamsWidget.setObjectName("allParamsWidget")
        self.allParamsLayout.addWidget(self.allParamsWidget)
        self.paramsLayout.addLayout(self.allParamsLayout)
        self.verticalLayout.addLayout(self.paramsLayout)

        self.retranslateUi(editParameter)
        self.buttonBox.accepted.connect(editParameter.accept)
        self.buttonBox.rejected.connect(editParameter.reject)
        QtCore.QMetaObject.connectSlotsByName(editParameter)

    def retranslateUi(self, editParameter):
        _translate = QtCore.QCoreApplication.translate
        editParameter.setWindowTitle(_translate("editParameter", "Dialog"))
        self.deviceLabel.setText(_translate("editParameter", "Device"))
        self.activeParamsLabel.setText(_translate("editParameter", "Active Parameters"))
        self.addParamButton.setText(_translate("editParameter", "<<"))
        self.delParamButton.setText(_translate("editParameter", ">>"))
        self.allParamsLabel.setText(_translate("editParameter", "All Parameters"))

