# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(260, 0, 321, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 251, 181))
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 54, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 91, 21))
        self.label_5.setObjectName("label_5")
        self.toolButton = QtWidgets.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(90, 150, 24, 21))
        self.toolButton.setObjectName("toolButton")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(120, 150, 41, 20))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(160, 150, 41, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 40, 134, 110))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(160, 40, 89, 103))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.progressBar = QtWidgets.QProgressBar(self.widget1)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 180, 241, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget2 = QtWidgets.QWidget(self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 231, 31))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.widget3 = QtWidgets.QWidget(self.groupBox_2)
        self.widget3.setGeometry(QtCore.QRect(10, 50, 151, 181))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_9.addWidget(self.lineEdit_38)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_9.addWidget(self.lineEdit_35)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.horizontalLayout_9.addWidget(self.lineEdit_36)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_10.addWidget(self.lineEdit_39)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.horizontalLayout_10.addWidget(self.lineEdit_40)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_10.addWidget(self.lineEdit_41)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.horizontalLayout_11.addWidget(self.lineEdit_43)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.horizontalLayout_11.addWidget(self.lineEdit_44)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.horizontalLayout_11.addWidget(self.lineEdit_45)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.horizontalLayout_12.addWidget(self.lineEdit_47)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.horizontalLayout_12.addWidget(self.lineEdit_48)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.horizontalLayout_12.addWidget(self.lineEdit_49)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.horizontalLayout_13.addWidget(self.lineEdit_51)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.horizontalLayout_13.addWidget(self.lineEdit_52)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.horizontalLayout_13.addWidget(self.lineEdit_53)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.horizontalLayout_14.addWidget(self.lineEdit_55)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.horizontalLayout_14.addWidget(self.lineEdit_56)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.horizontalLayout_14.addWidget(self.lineEdit_57)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.horizontalLayout_15.addWidget(self.lineEdit_59)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.horizontalLayout_15.addWidget(self.lineEdit_60)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.widget3)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.horizontalLayout_15.addWidget(self.lineEdit_61)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 260, 331, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(270, 20, 51, 22))
        self.pushButton.setObjectName("pushButton")
        self.widget4 = QtWidgets.QWidget(self.groupBox_3)
        self.widget4.setGeometry(QtCore.QRect(0, 40, 271, 116))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_4.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_4.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_4.addWidget(self.lineEdit_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_5.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_5.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_5.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_5.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_5.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_5.addWidget(self.lineEdit_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_7.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_7.addWidget(self.lineEdit_24)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_7.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_7.addWidget(self.lineEdit_26)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_7.addWidget(self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_7.addWidget(self.lineEdit_28)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_8.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_8.addWidget(self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_8.addWidget(self.lineEdit_31)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_8.addWidget(self.lineEdit_32)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_8.addWidget(self.lineEdit_33)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.widget4)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_8.addWidget(self.lineEdit_34)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.widget5 = QtWidgets.QWidget(self.groupBox_3)
        self.widget5.setGeometry(QtCore.QRect(1, 21, 271, 21))
        self.widget5.setObjectName("widget5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.widget5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.widget5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.widget5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.widget5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.groupBox.raise_()
        self.graphicsView.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.lineEdit_35.raise_()
        self.lineEdit_36.raise_()
        self.lineEdit_38.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevices = QtWidgets.QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuExperiment = QtWidgets.QMenu(self.menubar)
        self.menuExperiment.setObjectName("menuExperiment")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menu2D_Sweep = QtWidgets.QMenu(self.menubar)
        self.menu2D_Sweep.setObjectName("menu2D_Sweep")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevices.menuAction())
        self.menubar.addAction(self.menuExperiment.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menu2D_Sweep.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Variable scan"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Time"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Vbg"))
        self.label_5.setText(_translate("MainWindow", "Data acquisition"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.checkBox.setText(_translate("MainWindow", "T"))
        self.checkBox_2.setText(_translate("MainWindow", "B"))
        self.label.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "End"))
        self.label_3.setText(_translate("MainWindow", "Step"))
        self.label_4.setText(_translate("MainWindow", "Step/s"))
        self.checkBox_3.setText(_translate("MainWindow", "Reverse"))
        self.checkBox_4.setText(_translate("MainWindow", "Stop at end"))
        self.pushButton_2.setText(_translate("MainWindow", "Begin"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Input"))
        self.label_12.setText(_translate("MainWindow", "Channel"))
        self.label_13.setText(_translate("MainWindow", "Name"))
        self.label_14.setText(_translate("MainWindow", "Value"))
        self.label_15.setText(_translate("MainWindow", "Require?"))
        self.lineEdit_38.setText(_translate("MainWindow", "Temp"))
        self.lineEdit_35.setText(_translate("MainWindow", "T"))
        self.lineEdit_39.setText(_translate("MainWindow", "Field"))
        self.lineEdit_40.setText(_translate("MainWindow", "B"))
        self.lineEdit_43.setText(_translate("MainWindow", "in0"))
        self.lineEdit_47.setText(_translate("MainWindow", "in1"))
        self.lineEdit_51.setText(_translate("MainWindow", "in2"))
        self.lineEdit_55.setText(_translate("MainWindow", "in3"))
        self.lineEdit_59.setText(_translate("MainWindow", "in4"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Output"))
        self.pushButton.setText(_translate("MainWindow", "Update"))
        self.lineEdit_5.setText(_translate("MainWindow", "Time"))
        self.lineEdit_11.setText(_translate("MainWindow", "O0"))
        self.lineEdit_23.setText(_translate("MainWindow", "O1"))
        self.lineEdit_29.setText(_translate("MainWindow", "O2"))
        self.label_7.setText(_translate("MainWindow", "Variable"))
        self.label_6.setText(_translate("MainWindow", "Value"))
        self.label_9.setText(_translate("MainWindow", "Start"))
        self.label_8.setText(_translate("MainWindow", "End"))
        self.label_10.setText(_translate("MainWindow", "Step/s"))
        self.label_11.setText(_translate("MainWindow", "Step"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDevices.setTitle(_translate("MainWindow", "Devices"))
        self.menuExperiment.setTitle(_translate("MainWindow", "Experiment"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menu2D_Sweep.setTitle(_translate("MainWindow", "2D Sweep"))

