# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MeasureIt(object):
    def setupUi(self, MeasureIt):
        MeasureIt.setObjectName("MeasureIt")
        MeasureIt.resize(712, 500)
        self.centralwidget = QtWidgets.QWidget(MeasureIt)
        self.centralwidget.setObjectName("centralwidget")
        self.scanGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.scanGroupBox.setGeometry(QtCore.QRect(10, 10, 341, 171))
        self.scanGroupBox.setObjectName("scanGroupBox")
        self.scanParameterBox = QtWidgets.QComboBox(self.scanGroupBox)
        self.scanParameterBox.setGeometry(QtCore.QRect(70, 20, 81, 22))
        self.scanParameterBox.setObjectName("scanParameterBox")
        self.scanParameterBox.addItem("")
        self.scanParameterBox.addItem("")
        self.scanParameterBox.addItem("")
        self.layoutWidget = QtWidgets.QWidget(self.scanGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 151, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.scanHorizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.scanHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scanHorizontalLayout.setObjectName("scanHorizontalLayout")
        self.scanLabelVerticalLayout = QtWidgets.QVBoxLayout()
        self.scanLabelVerticalLayout.setObjectName("scanLabelVerticalLayout")
        self.startLabel = QtWidgets.QLabel(self.layoutWidget)
        self.startLabel.setObjectName("startLabel")
        self.scanLabelVerticalLayout.addWidget(self.startLabel)
        self.endLabel = QtWidgets.QLabel(self.layoutWidget)
        self.endLabel.setObjectName("endLabel")
        self.scanLabelVerticalLayout.addWidget(self.endLabel)
        self.stepLabel = QtWidgets.QLabel(self.layoutWidget)
        self.stepLabel.setObjectName("stepLabel")
        self.scanLabelVerticalLayout.addWidget(self.stepLabel)
        self.stepsecLabel = QtWidgets.QLabel(self.layoutWidget)
        self.stepsecLabel.setObjectName("stepsecLabel")
        self.scanLabelVerticalLayout.addWidget(self.stepsecLabel)
        self.scanHorizontalLayout.addLayout(self.scanLabelVerticalLayout)
        self.scanValuesLayout = QtWidgets.QVBoxLayout()
        self.scanValuesLayout.setObjectName("scanValuesLayout")
        self.startEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.startEdit.setObjectName("startEdit")
        self.scanValuesLayout.addWidget(self.startEdit)
        self.endEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.endEdit.setObjectName("endEdit")
        self.scanValuesLayout.addWidget(self.endEdit)
        self.stepEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.stepEdit.setObjectName("stepEdit")
        self.scanValuesLayout.addWidget(self.stepEdit)
        self.stepsecEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.stepsecEdit.setObjectName("stepsecEdit")
        self.scanValuesLayout.addWidget(self.stepsecEdit)
        self.scanHorizontalLayout.addLayout(self.scanValuesLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.scanGroupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 50, 110, 115))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bidirectionalBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.bidirectionalBox.setObjectName("bidirectionalBox")
        self.verticalLayout_3.addWidget(self.bidirectionalBox)
        self.continualBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.continualBox.setObjectName("continualBox")
        self.verticalLayout_3.addWidget(self.continualBox)
        self.saveBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.saveBox.setChecked(True)
        self.saveBox.setObjectName("saveBox")
        self.verticalLayout_3.addWidget(self.saveBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.scanParameterLabel = QtWidgets.QLabel(self.scanGroupBox)
        self.scanParameterLabel.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.scanParameterLabel.setObjectName("scanParameterLabel")
        self.inputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.inputGroupBox.setGeometry(QtCore.QRect(10, 190, 341, 251))
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.editParameterButton = QtWidgets.QToolButton(self.inputGroupBox)
        self.editParameterButton.setGeometry(QtCore.QRect(120, 220, 91, 21))
        self.editParameterButton.setObjectName("editParameterButton")
        self.parameterTable = QtWidgets.QTableWidget(self.inputGroupBox)
        self.parameterTable.setGeometry(QtCore.QRect(10, 20, 321, 192))
        self.parameterTable.setObjectName("parameterTable")
        self.parameterTable.setColumnCount(4)
        self.parameterTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parameterTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameterTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameterTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameterTable.setHorizontalHeaderItem(3, item)
        self.parameterTable.horizontalHeader().setCascadingSectionResizes(True)
        self.parameterTable.horizontalHeader().setDefaultSectionSize(79)
        self.parameterTable.horizontalHeader().setMinimumSectionSize(10)
        self.parameterTable.horizontalHeader().setSortIndicatorShown(True)
        self.parameterTable.horizontalHeader().setStretchLastSection(True)
        self.outputGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.outputGroupBox.setGeometry(QtCore.QRect(370, 290, 331, 171))
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.pushButton = QtWidgets.QPushButton(self.outputGroupBox)
        self.pushButton.setGeometry(QtCore.QRect(270, 20, 51, 22))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget2 = QtWidgets.QWidget(self.outputGroupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 40, 358, 116))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_4.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_4.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_4.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_4.addWidget(self.lineEdit_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_5.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_5.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_5.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_5.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_5.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_5.addWidget(self.lineEdit_16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_7.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_7.addWidget(self.lineEdit_24)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_7.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_7.addWidget(self.lineEdit_26)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_7.addWidget(self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_7.addWidget(self.lineEdit_28)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_8.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_8.addWidget(self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_8.addWidget(self.lineEdit_31)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_8.addWidget(self.lineEdit_32)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_8.addWidget(self.lineEdit_33)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_8.addWidget(self.lineEdit_34)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.layoutWidget3 = QtWidgets.QWidget(self.outputGroupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(1, 21, 271, 21))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(400, 120, 108, 23))
        self.startButton.setObjectName("startButton")
        self.pauseButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(400, 160, 108, 23))
        self.pauseButton.setObjectName("pauseButton")
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setGeometry(QtCore.QRect(400, 200, 108, 23))
        self.endButton.setObjectName("endButton")
        MeasureIt.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MeasureIt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDevices = QtWidgets.QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuExperiment = QtWidgets.QMenu(self.menubar)
        self.menuExperiment.setObjectName("menuExperiment")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menu2D_Sweep = QtWidgets.QMenu(self.menubar)
        self.menu2D_Sweep.setObjectName("menu2D_Sweep")
        MeasureIt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MeasureIt)
        self.statusbar.setObjectName("statusbar")
        MeasureIt.setStatusBar(self.statusbar)
        self.addDeviceAction = QtWidgets.QAction(MeasureIt)
        self.addDeviceAction.setObjectName("addDeviceAction")
        self.actionQuit = QtWidgets.QAction(MeasureIt)
        self.actionQuit.setObjectName("actionQuit")
        self.removeDeviceAction = QtWidgets.QAction(MeasureIt)
        self.removeDeviceAction.setObjectName("removeDeviceAction")
        self.menuFile.addAction(self.actionQuit)
        self.menuDevices.addAction(self.addDeviceAction)
        self.menuDevices.addAction(self.removeDeviceAction)
        self.menuDevices.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevices.menuAction())
        self.menubar.addAction(self.menuExperiment.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menu2D_Sweep.menuAction())

        self.retranslateUi(MeasureIt)
        QtCore.QMetaObject.connectSlotsByName(MeasureIt)

    def retranslateUi(self, MeasureIt):
        _translate = QtCore.QCoreApplication.translate
        MeasureIt.setWindowTitle(_translate("MeasureIt", "MainWindow"))
        self.scanGroupBox.setTitle(_translate("MeasureIt", "Variable scan"))
        self.scanParameterBox.setItemText(0, _translate("MeasureIt", "(none)"))
        self.scanParameterBox.setItemText(1, _translate("MeasureIt", "Time"))
        self.scanParameterBox.setItemText(2, _translate("MeasureIt", "Vbg"))
        self.startLabel.setText(_translate("MeasureIt", "Start"))
        self.endLabel.setText(_translate("MeasureIt", "End"))
        self.stepLabel.setText(_translate("MeasureIt", "Step"))
        self.stepsecLabel.setText(_translate("MeasureIt", "Step/sec"))
        self.bidirectionalBox.setText(_translate("MeasureIt", "Bidirectional"))
        self.continualBox.setText(_translate("MeasureIt", "Continual"))
        self.saveBox.setText(_translate("MeasureIt", "Save data"))
        self.checkBox_2.setText(_translate("MeasureIt", "Live plot"))
        self.scanParameterLabel.setText(_translate("MeasureIt", "Parameter:"))
        self.inputGroupBox.setTitle(_translate("MeasureIt", "Input"))
        self.editParameterButton.setText(_translate("MeasureIt", "Edit Parameters"))
        item = self.parameterTable.horizontalHeaderItem(0)
        item.setText(_translate("MeasureIt", "Parameter"))
        item = self.parameterTable.horizontalHeaderItem(1)
        item.setText(_translate("MeasureIt", "Name"))
        item = self.parameterTable.horizontalHeaderItem(2)
        item.setText(_translate("MeasureIt", "Value"))
        item = self.parameterTable.horizontalHeaderItem(3)
        item.setText(_translate("MeasureIt", "Update?"))
        self.outputGroupBox.setTitle(_translate("MeasureIt", "Output"))
        self.pushButton.setText(_translate("MeasureIt", "Update"))
        self.lineEdit_5.setText(_translate("MeasureIt", "Time"))
        self.lineEdit_11.setText(_translate("MeasureIt", "O0"))
        self.lineEdit_23.setText(_translate("MeasureIt", "O1"))
        self.lineEdit_29.setText(_translate("MeasureIt", "O2"))
        self.label_7.setText(_translate("MeasureIt", "Variable"))
        self.label_6.setText(_translate("MeasureIt", "Value"))
        self.label_9.setText(_translate("MeasureIt", "Start"))
        self.label_8.setText(_translate("MeasureIt", "End"))
        self.label_10.setText(_translate("MeasureIt", "Step/s"))
        self.label_11.setText(_translate("MeasureIt", "Step"))
        self.startButton.setText(_translate("MeasureIt", "Start"))
        self.pauseButton.setText(_translate("MeasureIt", "Pause"))
        self.endButton.setText(_translate("MeasureIt", "End"))
        self.menuFile.setTitle(_translate("MeasureIt", "File"))
        self.menuDevices.setTitle(_translate("MeasureIt", "Devices"))
        self.menuExperiment.setTitle(_translate("MeasureIt", "Experiment"))
        self.menuData.setTitle(_translate("MeasureIt", "Data"))
        self.menu2D_Sweep.setTitle(_translate("MeasureIt", "2D Sweep"))
        self.addDeviceAction.setText(_translate("MeasureIt", "Add device..."))
        self.actionQuit.setText(_translate("MeasureIt", "Quit"))
        self.actionQuit.setShortcut(_translate("MeasureIt", "Ctrl+Q"))
        self.removeDeviceAction.setText(_translate("MeasureIt", "Remove device..."))

